### ISSUE TITLE
Getting Error as Error Domain=NSURLErrorDomain Code=-1012 in post Tweet

### ISSUE THREAD

**Issue by dixakatiyar87** [fhsjaagshs/FHSTwitterEngine#117] opened 2016-07-03 18:39 UTC
Hi, 
I am using Demo provided with  FHSTwitterEngine of both Objective C and Swift using Key and Secret provided in the demo as well as with new app key and secret as well.

Oath2 login gives me success while post tweet gives error as below:

**Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLStringKey=https://api.twitter.com/1.1/statuses/update.json, NSUnderlyingError=0x7fa2d0732ca0 {Error Domain=kCFErrorDomainCFNetwork Code=-1012 "(null)" UserInfo={_kCFURLErrorAuthFailedResponseKey=<CFURLResponse 0x7fa2d079ad90 [0x1053c97b0]>{url = https://api.twitter.com/1.1/statuses/update.json}}}, NSErrorFailingURLKey=https://api.twitter.com/1.1/statuses/update.json}**

**Comment by ReadmeCritic** [comment] 2016-07-08 16:06
Just tested the objc demo as is, works correctly
I would check your key and secret

**Comment by fabionapodano** [comment] 2016-08-05 14:49
not working for me also. nor the demo, nor my own code. getting same error

**Comment by fabionapodano** [comment] 2016-08-05 15:10
my issue seemed to be caused by not specifying an URL callboack for OAuth in dev.twitter.com app settings. putting an existing URL fixed the issue

**Comment by dkhamsing** [comment] 2016-08-05 15:16
Thanks for the report
Closing

**Closed by dkhamsing** 2016-08-05 15:16 UTC
